
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cosc349_database
    ports:
      - "1234:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data even after container is removed
      - ./scripts:/docker-entrypoint-initdb.d/ # Mount the database script


  request-service:
    container_name : request-service
    build:
      context: .
      dockerfile: ./request-service/Dockerfile
    depends_on:
        - db
    ports:
        - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: cosc349_database

volumes:
  postgres_data:  # This defines the postgres_data volume
